
public class Main {

	//Stack working the way it should.
	public static void main(String[] args) throws Exception {
		ArrayStack as = new ArrayStack();
		as.push(1, 1);
		as.push(2, 1);
		as.push(3, 1);
		as.push(4, 1);
		as.push(5, 1);
		as.push(6, 1);
		as.push(7, 1);
		as.push(8, 1);
		as.push(9, 1);
		as.push(10, 1);
		as.push(1, 1);
		as.push(2, 1);
		as.push(3, 1);
		as.push(4, 1);
		as.push(5, 1);
		as.push(6, 1);
		as.push(7, 1);
		as.push(8, 1);
		as.push(9, 1);
		as.push(10, 1);
		as.push(1, 1);
		as.push(2, 1);
		as.push(3, 1);
		as.push(4, 1);
		as.push(5, 1);
		as.push(6, 1);
		as.push(7, 1);
		as.push(8, 1);
		as.push(9, 1);
		as.push(10, 1);
		as.push(1, 1);
		as.push(2, 1);
		as.push(3, 1);
		as.push(4, 1);
		as.push(5, 1);
		as.push(6, 1);
		as.push(7, 1);
		as.push(8, 1);
		as.push(9, 1);
		as.push(10, 1);
		as.push(1, 1);
		as.push(2, 1);
		as.push(3, 1);
		as.push(4, 1);
		as.push(5, 1);
		as.push(6, 1);
		as.push(7, 1);
		as.push(8, 1);
		as.push(9, 1);
		as.push(10, 1);
		as.push(1, 1);
		as.push(2, 1);
		as.push(3, 1);
		as.push(4, 1);
		as.push(5, 1);
		as.push(6, 1);
		as.push(7, 1);
		as.push(8, 1);
		as.push(9, 1);
		as.push(10, 1);
		as.push(1, 1);
		as.push(2, 1);
		as.push(3, 1);
		as.push(4, 1);
		as.push(5, 1);
		as.push(6, 1);
		as.push(7, 1);
		as.push(8, 1);
		as.push(9, 1);
		as.push(10, 1);
		as.push(1, 1);
		as.push(2, 1);
		as.push(3, 1);
		as.push(4, 1);
		as.push(5, 1);
		as.push(6, 1);
		as.push(7, 1);
		as.push(8, 1);
		as.push(9, 1);
		as.push(10, 1);
		as.push(1, 1);
		as.push(2, 1);
		as.push(3, 1);
		as.push(4, 1);
		as.push(5, 1);
		as.push(6, 1);
		as.push(7, 1);
		as.push(8, 1);
		as.push(9, 1);
		as.push(10, 1);
		as.push(1, 1);
		as.push(2, 1);
		as.push(3, 1);
		as.push(4, 1);
		as.push(5, 1);
		as.push(6, 1);
		as.push(7, 1);
		as.push(8, 1);
		as.push(9, 1);
		as.push(10, 1);
		//as.push(1, 1);
		//as.push(1, 1);
		
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		as.pop(1);
		
		as.push(1909090, 1);
		
		System.out.println(as.pop(1));

	}
}
